[package]
name = "search_client"
version = "0.1.0"
authors = ["Matt Doughty <matt.doughty@mhra.gov.uk>", "Craig Anderson <craig.anderson@red-badger.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.26"
async-trait = "0.1.24"
reqwest = { version = "0.10.4", features = ["json"] }
serde = "1.0.105"
serde_derive = "1.0.105"
serde_json = "1.0"
tracing = { version = "0.1", features = ["attributes"] }
