name: $(Date:yyyyMMdd)$(Rev:.r)
jobs:
  - job: medicines
    displayName: Build Medicines
    pool:
      vmImage: ubuntu-18.04
    steps:
      - script: |
          export CARGO_HOME="$HOME/.cargo"
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Install nightly Rust
      - script: |
          cd medicines && cargo test
        displayName: Run tests
