apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  type: LoadBalancer
  loadBalancerIP: 51.132.9.162
  ports:
    - name: http
      port: 8000
      targetPort: 80
