name: $(Date:yyyyMMdd)$(Rev:.r)

                  # $(containerRegistry)/$(imageRepository):$(tag)

stages:
  - stage: Build
    displayName: Build stage
    jobs:  
    - job: Build
      displayName: Build job
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: products/api
          dockerfile: $(Build.SourcesDirectory)/medicines/api/Dockerfile
          containerRegistry: mhraproductsdevregistry
          tags: |
            latest
      - task: PublishPipelineArtifact@1
        inputs:
          artifactName: manifests
          path:  $(Build.SourcesDirectory)/medicines/api/infrastructure/development
####################
  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    jobs:
    - deployment: Deploy
      displayName: Deploy job
      pool:
        vmImage: ubuntu-latest
      environment: development
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                artifactName: manifests
                downloadPath: $(System.ArtifactsDirectory)/medicines/api/infrastructure/development

            - task: KubernetesManifest@0
              displayName: Create imagePullSecret
              inputs:
                action: createSecret
                secretName: cluster-cred
                namespace: default
                kubernetesServiceConnection: aks
                dockerRegistryEndpoint: mhraproductsdevregistry

            - task: KubernetesManifest@0
              displayName: Deploy to Kubernetes cluster
              inputs:
                kubernetesServiceConnection: aks
                action: deploy
                namespace: default
                manifests: |
                  $(System.ArtifactsDirectory)/medicines/api/infrastructure/development/deployment.yml
                  $(System.ArtifactsDirectory)/medicines/api/infrastructure/development/service.yml
                  $(System.ArtifactsDirectory)/medicines/api/infrastructure/development/virtual-service.yml
                imagePullSecrets: |
                  cluster-cred
                containers: |
                  mhraproductsdevregistry.azurecr.io/products/api:latest