[package]
name = "api"
version = "0.1.0"
authors = ["Stuart Harris <stuart.harris@red-badger.com>", "Robin James Kerrison <robinjames.kerrison@red-badger.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.0.0"
actix-web = "2.0.0"
env_logger = "0.7.1"
juniper = { git = "https://github.com/graphql-rust/juniper" }
listenfd = "0.3.3"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.44"