apiVersion: v1
kind: Service
metadata:
  name: zeebe-nginx-ingress-controller
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeebe-nginx-ingress-controller
spec:
  template:
    spec:
      containers:
        - name: nginx-ingress-controller
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              hostPort: 443
              protocol: TCP
      nodeSelector:
        ingress-ready: "true"
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Equal
          effect: NoSchedule
