[package]
name = "search"
version = "0.1.0"
authors = ["Matt Doughty <matt.doughty@mhra.gov.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.12.35"
tokio-core = "0.1.17"
futures = "0.1.29"