apiVersion: install.istio.io/v1alpha3
kind: IstioControlPlane
spec:
  # Use the default profile as the base
  # More details at: https://istio.io/docs/setup/additional-setup/config-profiles/
  profile: default
  values:
    global:
      # Ensure that the Istio pods are only scheduled to run on Linux nodes
      defaultNodeSelector:
        beta.kubernetes.io/os: linux
      # Enable mutual TLS for the control plane
      controlPlaneSecurityEnabled: true
      mtls:
        # Require all service to service communication to have mtls
        enabled: false
    gateways:
      istio-ingressgateway:
        loadBalancerIP: 51.105.53.132
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-resource-group: products-dev
