apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeebe-operate
spec:
  template:
    spec:
      containers:
        - name: operate
          resources:
            requests:
              cpu: 128m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
