[package]
name = "hello-world"
version = "0.1.0"
authors = ["stuart.harris@red-badger.com"]
edition = "2018"

[dependencies]
async-std = { version = "1.5.0", features = ["unstable", "attributes"] }
tide = { git = "https://github.com/http-rs/tide", branch = "errors" }
