[package]
name = "doc_index_updater"
version = "0.1.0"
authors = ["Stuart Harris <stuart.harris@red-badger.com>", "Robin James Kerrison <robinjames.kerrison@red-badger.com>", "Matt Doughty <matt.doughty@red-badger.com>", "Pedro Martin <pedro.martin@red-badger.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azure_sdk_service_bus = { git = "https://github.com/redbadger/AzureSDKForRust" }
azure_sdk_core = { git = "https://github.com/redbadger/AzureSDKForRust" }
log = "0.4"
pretty_env_logger = "0.4.0"
redis = { version = "0.15.1", features = ["tokio-rt-core"] }
serde = "1.0.104"
serde_derive = "1.0.104"
time = "0.1"
tokio = { version = "0.2", features = ["macros"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
warp = "0.2"


[dev-dependencies]
test-case = "1.0.0"
