apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master
spec:
  template:
    spec:
      containers:
        - name: "elasticsearch"
          resources:
            limits:
              cpu: 1000m
              memory: 1.5Gi
            requests:
              cpu: 100m
              memory: 1.5Gi
