apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "zeebe-zeebe"
spec:
  template:
    spec:
      containers:
        - name: zeebe
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 1Gi
