---
# Source: zeebe-full/charts/zeebe/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "zeebe-zeebe"
  labels:
    app.kubernetes.io/name: zeebe
    app.kubernetes.io/instance: zeebe
    app: "zeebe-zeebe"
    app: zeebe
  annotations:   
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: zeebe
      app.kubernetes.io/instance: zeebe
      app: "zeebe-zeebe"
  serviceName: "zeebe-zeebe"
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zeebe
        app.kubernetes.io/instance: zeebe
        app: "zeebe-zeebe"
      annotations:   
    spec:
      initContainers:    
      containers:
      - name: zeebe
        image: "camunda/zeebe:0.22.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: ZEEBE_LOG_LEVEL
          value: debug
        - name: ZEEBE_PARTITIONS_COUNT
          value: "3"
        - name: ZEEBE_CLUSTER_SIZE
          value: "3"
        - name: ZEEBE_REPLICATION_FACTOR
          value: "3"
        - name: JAVA_TOOL_OPTIONS
          value:
            "-XX:+UseParallelGC \n-XX:MinHeapFreeRatio=5\n-XX:MaxHeapFreeRatio=10\n-XX:MaxRAMPercentage=25.0
              \n-XX:GCTimeRatio=4 \n-XX:AdaptiveSizePolicyWeight=90\n-XX:+PrintFlagsFinal\n-Xmx4g\n-Xms4g\n-XX:+HeapDumpOnOutOfMemoryError\n-XX:HeapDumpPath=/usr/local/zeebe/data\n-XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log\n"
        ports:
        - containerPort: 9600
          name: http
        - containerPort: 26500
          name: gateway
        - containerPort: 26501
          name: command
        - containerPort: 26502
          name: internal
        readinessProbe:
          httpGet:
            path: /ready
            port: 9600
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi
        volumeMounts:
        - name: config
          mountPath: /usr/local/zeebe/conf/zeebe.cfg.toml
          subPath: zeebe.cfg.toml
        - name: config
          mountPath: /usr/local/bin/startup.sh
          subPath: startup.sh
        - name: data
          mountPath: /usr/local/zeebe/data
      volumes:
      - name: config
        configMap:
          name: "zeebe-zeebe"
          defaultMode: 0744
      securityContext:
        null
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: "10Gi"
