apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls
spec:
  secretName: tls
  dnsNames:
    - $PUBLIC_URL
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - $PUBLIC_URL
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
