apiVersion: install.istio.io/v1alpha3
kind: IstioControlPlane
spec:
  # Use the default profile as the base
  # More details at: https://istio.io/docs/setup/additional-setup/config-profiles/
  profile: default
  values:
    global:
      defaultNodeSelector:
        beta.kubernetes.io/os: linux
      controlPlaneSecurityEnabled: true
      mtls:
        enabled: true
    gateways:
      istio-ingressgateway:
        loadBalancerIP: 51.132.33.207
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-resource-group: MHRA-dev
