name: api-master

on:
  push:
    branches:
      - master
    paths:
      - medicines/api/**
      - .github/workflows/api-master.yaml

jobs:
  build-and-test:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Test
        working-directory: ./medicines/search-client
        run: cargo test

      - name: Build, test and push Docker image
        working-directory: ./medicines/api
        run: |
          TAG="$(git rev-parse --short=7 ${{ github.sha }})"
          make ci-master tag=$TAG
          DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' ${IMAGE}:${TAG})"
          echo ::set-env name=TAG::$TAG
          echo ::set-env name=DIGEST::$DIGEST
