name: api-branch

on:
  push:
    branches:
      - "**"
      - "!master"
    paths:
      - medicines/api/**
      - .github/workflows/api-branch.yaml

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Test
        working-directory: ./medicines/api
        run: cargo test

      - name: Build docker image
        working-directory: ./medicines/api
        run: docker build .
