name: doc-index-updater

on:
  push:
    paths:
      - medicines/doc-index-updater/**
      - .github/workflows/doc-index-updater.yaml

env:
  IMAGE: mhraproductsdevelopmentregistry.azurecr.io/products/doc-index-updater

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          path: products

      - name: Get tag
        run: |
          echo ::set-env name=TAG::"$(git rev-parse --short=7 ${{ github.sha }})"

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: mhraproductsdevelopmentregistry.azurecr.io
          username: mhraproductsdevelopmentregistry
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build, test and push Docker image
        working-directory: ./products/medicines/doc-index-updater
        run: make ci tag=$TAG

      - name: Get image digest
        run: echo ::set-env name=DIGEST::"$(docker inspect --format='{{index .RepoDigests 0}}' ${IMAGE})"

      - name: Clone Deployments repo
        uses: actions/checkout@v2
        with:
          repository: MHRA/deployments
          path: deployments
          token: ${{ secrets.DEPLOYMENTS_REPO_TOKEN }}

      - name: Update image tag
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 3.4.0
          command: |
            set -eux
            cd deployments/doc-index-updater/overlays/non-prod

            kustomize edit set image $DIGEST

            git config --local user.email "CD.no.reply@mhra.gov.uk"
            git config --local user.name "MHRA CI/CD"
            git commit -a -m "CI: Update image tag"
            git push
