name: doc-index-updater-master

on:
  push:
    branches:
      - master
    paths:
      - medicines/doc-index-updater/**
      - medicines/search-client/**
      - .github/workflows/doc-index-updater-master.yaml
      - .github/workflows/doc-index-updater-release.yaml

env:
  IMAGE: mhraproductsnonprodregistry.azurecr.io/products/doc-index-updater

jobs:
  build-and-test:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          path: products

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: mhraproductsnonprodregistry.azurecr.io
          username: mhraproductsnonprodregistry
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set .env.build
        working-directory: ./products/medicines/doc-index-updater
        run: echo "SCCACHE_AZURE_CONNECTION_STRING=\"$SCCACHE_AZURE_CONNECTION_STRING\"" > .env.build
        env:
          SCCACHE_AZURE_CONNECTION_STRING: ${{ secrets.SCCACHE_AZURE_CONNECTION_STRING }}

      - name: Build, test and push Docker image
        working-directory: ./products/medicines/doc-index-updater
        run: |
          TAG="$(git rev-parse --short=7 ${{ github.sha }})"
          make ci-master tag=$TAG
          DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' ${IMAGE}:${TAG})"
          echo ::set-env name=TAG::$TAG
          echo ::set-env name=DIGEST::$DIGEST

      - name: Clone Deployments repo
        uses: actions/checkout@v2
        with:
          repository: MHRA/deployments
          path: deployments
          token: ${{ secrets.DEPLOYMENTS_REPO_TOKEN }}

      - name: Update image tag
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 3.4.0
          command: |
            set -eux
            SOURCE="${PWD}/products/medicines/doc-index-updater/manifests/overlays/non-prod"
            DEST="${PWD}/deployments/doc-index-updater/non-prod"

            cd $SOURCE 
            kustomize edit set image $DIGEST
            mkdir -p "${DEST}"
            kustomize build . > "${DEST}/manifests.yaml"
            
            cd $DEST
            git config --local user.email "CD.no.reply@mhra.gov.uk"
            git config --local user.name "MHRA CI/CD"
            git add --all
            git diff-index --quiet HEAD || git commit -m "CI: Update image for $TAG"
            declare -i n
            n=0
            until [ $n -ge 5 ]
            do
              git push && break
              n+=1
              git pull --rebase
            done
