name: doc-index-updater-branch

on:
  pull_request:
    branches:
      - "master"
    paths:
      - rust-toolchain
      - medicines/doc-index-updater/**
      - medicines/search-client/**
      - .github/workflows/doc-index-updater-branch.yaml

env:
  IMAGE: mhraproductsdevelopmentregistry.azurecr.io/products/doc-index-updater

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          path: products

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: mhraproductsdevelopmentregistry.azurecr.io
          username: mhraproductsdevelopmentregistry
          password: ${{ secrets.DEVELOPMENT_REGISTRY_PASSWORD }}

      - name: Make toolchain version available in current directory
        run: cp products/rust-toolchain .

      - uses: actions-rs/toolchain@v1
        with:
          components: clippy

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            products/medicines/doc-index-updater/target
          key: cargo-${{ hashFiles('products/medicines/doc-index-updater/Cargo.lock') }}-1

      - name: Build and test doc-index-updater service
        working-directory: products/medicines/doc-index-updater
        env:
          REDIS_SERVER: redis
          REDIS_PORT: 6379
        run: |
          set -e
          cargo clippy --release -- -D warnings
          cargo build --release
          cargo test --release

      - name: Build and push Docker image
        working-directory: products/medicines/doc-index-updater
        run: |
          TAG="$(git rev-parse --short=7 ${{ github.sha }})"
          make ci-master tag=$TAG image=$IMAGE
          DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' ${IMAGE}:${TAG})"
          echo ::set-env name=TAG::$TAG
          echo ::set-env name=DIGEST::$DIGEST

      - name: Clone Deployments repo
        uses: actions/checkout@v2
        with:
          repository: MHRA/deployments
          path: deployments
          token: ${{ secrets.DEPLOYMENTS_REPO_TOKEN }}

      - name: Update image tag
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 3.4.0
          command: |
            set -eux
            SOURCE="${PWD}/products/medicines/doc-index-updater/manifests/overlays/dev"
            DEST="${PWD}/deployments/doc-index-updater/dev"

            cd $SOURCE 
            kustomize edit set image $DIGEST
            mkdir -p "${DEST}"
            kustomize build . > "${DEST}/manifests.yaml"

            cd $DEST
            git config --local user.email "CD.no.reply@mhra.gov.uk"
            git config --local user.name "MHRA CI/CD"
            git add --all
            git diff-index --quiet HEAD || git commit -m "CI: Update image for $TAG"
            declare -i n
            n=0
            until [ $n -ge 5 ]
            do
              git push && break
              n+=1
              git pull --rebase
            done
