name: medicines-api-release

on:
  push:
    tags:
      - medicinesapi.v*

env:
  NONPROD_IMAGE: mhraproductsnonprodregistry.azurecr.io/products/medicines-api
  PROD_IMAGE: mhraproducts4853registry.azurecr.io/products/medicines-api

jobs:
  build-and-test:
    name: Create release and deploy to production
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          path: products

      - name: Docker login to nonprod
        uses: azure/docker-login@v1
        with:
          login-server: mhraproductsnonprodregistry.azurecr.io
          username: mhraproductsnonprodregistry
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Create Docker tag
        working-directory: ./products/medicines/api
        run: |
          TAG="$(git rev-parse --short=7 ${{ github.sha }})"
          echo "TAG=$TAG" >>$GITHUB_ENV

      - name: Fetch image for tagged commit
        id: fetch-image
        continue-on-error: true
        working-directory: ./products/medicines/api
        run: |
          make docker-pull image=$NONPROD_IMAGE tag=$TAG

      - name: Docker login to prod
        uses: azure/docker-login@v1
        if: steps.fetch-image.outcome == 'success'
        with:
          login-server: mhraproducts4853registry.azurecr.io
          username: mhraproducts4853registry
          password: ${{ secrets.PROD_REGISTRY_PASSWORD }}

      - name: Push image for tagged commit
        if: steps.fetch-image.outcome == 'success'
        working-directory: ./products/medicines/api
        run: |
          make docker-retag image=$NONPROD_IMAGE new_image=$PROD_IMAGE tag=$TAG
          make docker-push image=$PROD_IMAGE tag=$TAG
          DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' ${PROD_IMAGE}:${TAG})"
          echo "DIGEST=$DIGEST" >>$GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: medicines-api release ${{ github.ref }}
          body: |
            Release of Medicines Api
          draft: false
          prerelease: false

      - name: Clone Deployments repo
        uses: actions/checkout@v2
        with:
          repository: MHRA/deployments
          path: deployments
          token: ${{ secrets.DEPLOYMENTS_REPO_TOKEN }}

      - name: Update image tag
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 3.4.0
          command: |
            set -ex
            SOURCE="${PWD}/products/manifests/medicines-api/overlays/prod"
            DEST="${PWD}/deployments/medicines-api/prod"
            DEST_MANIFESTS="${DEST}/manifests.yaml"

            cd $SOURCE
            mkdir -p "${DEST}"

            set +u
            if [[ -n "${DIGEST}" ]]; then 
              kustomize edit set image $DIGEST
            else
              cat "${DEST_MANIFESTS}" | awk '/image:/ {print}' | sed 's/image://' | xargs kustomize edit set image
            fi
            set -u

            kustomize build . > "${DEST_MANIFESTS}"

            cd $DEST
            git config --local user.email "CD.no.reply@mhra.gov.uk"
            git config --local user.name "MHRA CI/CD"
            git add --all
            git diff-index --quiet HEAD || git commit -m "CI: Update production image for $TAG"
            declare -i n
            n=0
            until [ $n -ge 5 ]
            do
              git push && break
              n+=1
              git pull --rebase
            done
