name: nibsc-web-branch

on:
  pull_request:
    branches:
      - "master"
    paths:
      - nibsc/web/**
      - .github/workflows/nibsc-web-branch.yaml

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.11"

      - name: Install modules
        working-directory: nibsc/web
        run: yarn install --frozen-lockfile

      - name: Build and export
        working-directory: nibsc/web
        run: yarn build && yarn export
