name: nibsc-web-master

on:
  push:
    branches:
      - master
    paths:
      - nibsc/web/**
      - .github/workflows/nibsc-web-branch.yaml

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version:
            "13.11"
            # Based on https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        name: Cache yarn dependencies
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('nibsc/web/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # See: https://github.com/zeit/next.js/blob/master/errors/no-cache.md
      - uses: actions/cache@v1
        name: Cache Next.js cache folder
        with:
          path: nibsc/web/.next/cache
          key: ${{ runner.os }}-next-js-${{ hashFiles('nibsc/web/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-next-js-

      - name: Install modules
        working-directory: nibsc/web
        run: yarn install --frozen-lockfile

      - name: Build and export
        working-directory: nibsc/web
        run: yarn build && yarn export

      - name: Deploy products web to static site in azure storage
        # master causes this step to fail so pointing to last working commit until fixed
        uses: lauchacarro/Azure-Storage-Action@9225056
        with:
          enabled-static-website: true
          folder: nibsc/web/dist
          connection-string: ${{ secrets.AZURE_STORAGE_NIBSC_WEB_CONNECTION_STRING_NONPROD }}
