name: storage-logger-execution

on:
  schedule:
    # 12pm every Friday
    - cron: "0 12 * * 5"

jobs:
  build-and-test:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          path: products

      - name: Test
        working-directory: ./products/medicines/storage-logger
        run: cargo test

      - name: Run storage log
        working-directory: ./products/medicines/storage-logger
        env:
          STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
          STORAGE_MASTER_KEY: ${{ secrets.STORAGE_MASTER_KEY }}
          STORAGE_CONTAINER_NAME: ${{ secrets.STORAGE_CONTAINER_NAME }}
          STORAGE_CONTAINER_BACKUP_NAME: ${{ secrets.STORAGE_CONTAINER_BACKUP_NAME }}
        run: cargo run
