name: transaction-log-file-creator-execution

on:
  schedule:
    # Midnight on the first day of every month
    - cron: "0 0 1 * *"

jobs:
  build-and-test:
    name: Test and Run
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          path: products

      - name: Make toolchain version available in current directory
        run: cp products/rust-toolchain .

      - uses: actions-rs/toolchain@v1
        with:
          components: clippy

      - name: Test
        working-directory: ./products/medicines/transaction-log-file-creator
        run: make test

      - name: Run storage log
        working-directory: ./products/medicines/transaction-log-file-creator
        env:
          LOG_STORAGE_ACCOUNT: ${{ secrets.LOG_STORAGE_ACCOUNT_PROD }}
          LOG_STORAGE_MASTER_KEY: ${{ secrets.LOG_STORAGE_MASTER_KEY_PROD }}
          LOG_STORAGE_CONTAINER: ${{ secrets.TRANSACTION_LOG_STORAGE_CONTAINER_NAME_PROD }}
        run: cargo run
