name: transaction-log-file-creator-branch

on:
  pull_request:
    branches:
      - "master"
    paths:
      - medicines/transaction-log-file-creator/**
      - .github/workflows/transaction-log-file-creator-branch.yaml

jobs:
  build-and-test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          path: products

      - name: Test
        working-directory: ./products/medicines/transaction-log-file-creator
        run: make test
