name: transaction-log-file-creator-ci

on:
  pull_request:
    paths:
      - medicines/transaction-log-file-creator/**
      - .github/workflows/transaction-log-file-creator-ci.yaml
  push:
    branches:
      - master
    paths:
      - medicines/transaction-log-file-creator/**
      - .github/workflows/transaction-log-file-creator-ci.yaml

jobs:
  build-and-test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          path: products

      - name: Make toolchain version available in current directory
        if: steps.filter.outputs.src == 'true'
        run: cp products/rust-toolchain .

      - uses: actions-rs/toolchain@v1
        with:
          components: clippy

      - name: Test
        working-directory: ./products/medicines/transaction-log-file-creator
        run: make test
